name: Build and deploy ASP.Net Core app to Azure Web App - PSUSWENG861MusicApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./MusicApp

      - name: dotnet publish
        run: dotnet publish MusicApp.csproj -c Release -o ./publish
        working-directory: ./MusicApp

      - name: List contents of the publish directory
        run: Get-ChildItem -Path ./publish -Force | Format-List
        working-directory: ./MusicApp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ./MusicApp/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: deploy  # This specifies a directory within the runner to place the downloaded artifacts.

      - name: List contents before deployment
        run: Get-ChildItem -Path ./deploy -Force | Format-List  # Lists the contents of the directory where artifacts are downloaded.

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2009CE209EAF40429BB556DA5CA7EB42 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8D7EF70BE44E47A6916AC938BDADD580 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1CA429A61E684448AD6F542B79203200 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'PSUSweng861MusicApp'
          package: './deploy'  # This should point to the directory where the artifact is downloaded.
